name: Build and Publish Docker Image on GitHub Container Registry
on:
# Décommenter la ligne ci-dessous pour déclencher le workflow à chaque publication de release
#   release:
#     types: [published]
  workflow_dispatch:

jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Récupération du tag git pour la version de l'image
      - name: Extract Version
        uses: damienaicheh/extract-version-from-tag-action@v1.1.0

      - name: Docker - Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/wavenet-be/wavenet-swa-builder
          tags: |
            ${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}
            latest
          labels: |
            version: ${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}