name: Check If Run From Tag

runs:
  using: "composite"
 
  steps:
  - name: Display Environment
    env:
      EVENT_CONTEXT: ${{ toJSON(github.event) }}
    run: |
      echo $EVENT_CONTEXT
      
  - name: Check if run from tag
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    run: |
      echo "This workflow must be run from a tag"
      exit 1
